spring:
  profiles:
    active: user1
  application:
    name: house-cloud-user

eureka:
  instance:
    hostname: 127.0.0.1
    # 心跳时间，即服务续约间隔时间，缺省为30秒
    lease-renewal-interval-in-seconds: 5
    # 发呆时间，即服务续约到期时间，缺省为90秒
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true # 开启健康检查，依赖spring-boot-starter-actuaor
    # 表示eureka client间隔多久去拉取服务注册信息，缺省为30秒。
    # 对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值
    registry-fetch-interval-seconds: 30

---
server:
  port: 8001

spring:
  profiles: user1

---
server:
  port: 8002

spring:
  profiles: user2
