spring:
  profiles:
    active: gateway1
  application:
    name: house-cloud-api-gateway

eureka:
  instance:
    hostname: 127.0.0.1
    # 心跳时间，即服务续约间隔时间，缺省为30秒
    lease-renewal-interval-in-seconds: 5
    # 发呆时间，即服务续约到期时间，缺省为90秒
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true # 开启健康检查，依赖spring-boot-starter-actuaor
    # 表示eureka client间隔多久去拉取服务注册信息，缺省为30秒。
    # 对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值
    registry-fetch-interval-seconds: 20

# spring-boot2.0 actuator配置
# 这个配置和1.X不一样
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: false
---
server:
  port: 8011

spring:
  profiles: gateway1

---
server:
  port: 8012

spring:
  profiles: gateway2
